
development:
  adapter  : mysql2
  database : flight_tracker_development
  encoding : utf8
  username : root
  password :
  host     : localhost

test:
  adapter  : mysql2
  database : flight_tracker_test
  encoding : utf8
  username : root
  password :
  host     : localhost

production:
  adapter  : mysql2
  database : flight_tracker_production
  encoding : utf8
  username : root
  password :
  host     : localhost